# Generated by Django 4.2.1 on 2023-06-05 13:52

from django.db import migrations, models
import storage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('bbd', models.DateTimeField(null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('country_of_disassembly', models.TextField(blank=True, null=True)),
                ('country_of_rearing', models.TextField(blank=True, null=True)),
                ('country_of_slaughter', models.TextField(blank=True, null=True)),
                ('cutting_plant_registration', models.TextField(blank=True, null=True)),
                ('code', models.PositiveBigIntegerField()),
                ('type', models.TextField()),
                ('item', models.JSONField(default=storage.models.item_default)),
                ('lot_number', models.TextField(blank=True, null=True)),
                ('slaughterhouse_registration', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='storageitem',
            constraint=models.UniqueConstraint(fields=('code', 'type'), name='unique_item'),
        ),
    ]
